### ISSUE TITLE
Visual builder for trees

### ISSUE THREAD

**Issue by fbennets** [open-decision/Prototype#56]
**Is your feature request related to a problem? Please describe.**
Building decision trees requires quite a lot of preparation when only done text-based. A visual and interactive way to build the trees makes it way easier for experts to construct a tree. 

**Describe the solution you'd like**
We should have a interactive way to visually build trees with:

- a zoomable canvas
- three types of nodes (such as square, rectangle and circle or different colours): start, content and end-nodes
- an interactive way to connect nodes by "drawing" a connection
- a panel on the right site to edit the node (which looks partly like the node-create view)
- a function to save the tree
- a function to load existing trees

**Technical implementation**
- we could define a AJAX endpoint that delivers the tree data as JSON
- than we could use one of the frameworks mentioned below to render the tree

Possible Frameworks:
- [jsPlumb](https://jsplumbtoolkit.com)
- [Go.js](https://gojs.net/latest/samples/index.html)
- [CytoscapeJS ](https://js.cytoscape.org)
- [JointJS](https://www.jointjs.com/opensource)
- [diagramJS](https://github.com/bpmn-io/diagram-js)
- [Draw2D](http://www.draw2d.org/draw2d/examples.html)
- [Vis Network](https://visjs.org)
or we could use the mighty [D3.js](https://d3js.org)

**Comment by PhilGarb** [comment]
I agree this would be a more approchable way to build a tree and the necessary functionality seems sensible to me. I think however in the technical implementation you are missing how the process of creation would be handled. Since this is the builder we propably do not have any data to render and would need the user to create a chart first. Therefore an AJAX endpoint can serve the data later, but for each tree there would need to be a creation. Then we can transform the data for use in different parts of the application and serve it on request.

Maybe it would be a good idea to first define exactly what kind of data and relation modelling we need before choosing. Questions I think should be answered first:
1. **What kinds of relationships do we have between nodes?** (Just linear or multiple relations?)
2. **What would be the "tree independent" data like the questions and possible answers?** (In the end that is the data we care about in other parts of the application)

The framework would then need to answer:
3. **How is data handled inside the framework and what is the output?** (In order to model relations properly there would need to be an export of some sort)
4. **What kind of diagram can be build?** (Some frameworks seem to be more focused towards Graphs while others are more about flowcharts. What we need depends on question 1)
5. **Does the framework support building a flowchart dynamically?** (I think some expect to receive data and then only display it)

The reason I am asking all these questions is that most of the frameworks seem to be more about data representation. The more typical use case for them would be to receive data and display it while we are mainly interested in the output of data to use it somewhere else.

**Comment by fbennets** [comment]
**1. What kinds of relationships do we have between nodes? (Just linear or multiple relations?)**
Most of them are linear, even though we can have "jumps" between different levels of the decision tree, some nodes will can be called by several others. We could block this behaviour for the MVP.

**2. What would be the "tree independent" data like the questions and possible answers? (In the end that is the data we care about in other parts of the application)**
I attached a screenshot from the DB with the data of a node.
![Screenshot_2020-01-20 Change node Django site admin](https://user-images.githubusercontent.com/35722762/72741772-3b110a00-3ba0-11ea-95c8-bb06fa6fbcab.png)


**3. How is data handled inside the framework and what is the output? (In order to model relations properly there would need to be an export of some sort)**
We should take a deeper look in the frameworks, most of them provide a convenient API that returns the relations and positions of nodes.

**4. What kind of diagram can be build? (Some frameworks seem to be more focused towards Graphs while others are more about flowcharts. What we need depends on question 1)**
I guess that we should focus the more flexible, flowchart oriented one. We want to provide a flexible solution to improve the user experience in the future.

**5. Does the framework support building a flowchart dynamically? (I think some expect to receive data and then only display it)**
I think most to, but I'll take a look into them and rate the flowcharts according to their capabilities.

**Comment by aaronrothmann** [comment]
Closed because this was the main reason to switch from the Django-based approach you will find in this Repo to the new React-Frontend you will find here: https://github.com/open-decision/Builder
The visual builder will not be added to the prototype.
